In [1]:
Part 1 -- Single Prediction

<class 'SyntaxError'>: invalid syntax (<ipython-input-1-3841f551f497>, line 1)

In [2]:
"""
weight = .1


def neural_network(input, weight):

    pred = input * weight
    return pred

blade_angle = [8.5, 9.5, 9.9, 9.0]
input = blade_angle[0]
pred = neural_network(input, weight)
print(pred)

for i in range(len(blade_angle)):
    pred = neural_network(blade_angle[i], weight)
    print(f"sensing {i}: input={blade_angle[i]} prediction={pred}")
"""

# ---- Weighted sum: pair-multiply, then add ----
def w_sum(a, b):
    assert len(a) == len(b)
    output = 0
    for i in range(len(a)):
        output += a[i] * b[i] # multiply and accumulate
    return output

# ---- Network with multiple inputs ----
weights = [0.1, 0.2, 0.0] # one weight per input

def neural_network(input, weights):
    pred = w_sum(input, weights)
    return pred

# ---- One sparring sensing: three readings ----
blade_angle = [8.5, 9.5, 9.9, 9.0] # degrees off-vertical
balance = [0.65, 0.80, 0.80, 0.90]
breath = [1.2, 1.3, 0.5, 1.0]

input = [blade_angle[0], balance[0], breath[0]]
pred = neural_network(input, weights)
print(pred) # 0.9800000000000001

0.9800000000000001


In [3]:
Part 2 -- Multiple Inputs: the weighted sum

<class 'SyntaxError'>: invalid syntax (<ipython-input-3-534d8f1085c5>, line 1)

In [4]:
import numpy as np

# Weighted sum function, takes input vector (a) and
# computes the dot product with weight vector (b)
# Returns weighted_sum (A.K.A. the dot product)
def w_sum(a, b):
    assert len(a) == len(b) #makes sure the vectors are the same length
    weighted_sum = 0 # init w_sum total to 0
    for i in range(len(a)):
        #For all of the inputs and weights, multiply the input at the i'th
        #index with the weight at the same index and add that to the w_sum total
        weighted_sum += a[i]*b[i]
    return weighted_sum

# Uses w_sum func to get the weighted sum of an input vector and weight vector
#returns the weighted sum
def neural_network(inputs, weights):
    pred = w_sum(inputs, weights)
    return pred

blade_angle = [8.5, 9.5, 9.9, 9.0] # degrees off-vertical
balance = [0.65, 0.80, 0.80, 0.90] # balance reading
breath = [1.2, 1.3, 0.5, 1.0] # exhalations per second

weights = [0.1, 0.2, 0.0]

sessions = [0 for _ in range(len(blade_angle))] #Init a vector that is the size of
# the total number of sessions with a placeholder val 0 to store each session's vals.

for i in range(len(blade_angle)):
    # Set each session's values to the corresponding session's values.
    sessions[i] = [blade_angle[i], balance[i], breath[i]]

scratch_preds = [0 for _ in range(len(sessions))] # Create vector of zeros to hold scratch
# preds for comparison with NumPy

for i in range(len(sessions)):
    # For each session, predict off of its values and the weights and store the pred in
    # scratch_preds
    pred = neural_network(sessions[i], weights)
    scratch_preds[i] = pred 
 
#---------------NumPy version---------------

# NumPy needs arrays to be np.arrays to be able to be used with the special np funcs.
np_weights = np.array(weights) #make np array of weights
np_sessions = np.array(sessions) #make equivalent np array of sessions

def np_neural_network(input, weights):
    # NumPy's built in .dot function acts just as the scratch w_sum func.
    pred = input.dot(weights)
    return pred

np_preds = np.zeros(len(sessions)) # Create vector of zeros to store NumPy preds for comparison.
#np.zeros creates a vector of zeros with the specified dimensions 

for i in range(len(sessions)):
    # Get the np_pred using the np_neural_network for every session and the weights
    # and store the pred in np_preds.
    np_pred = np_neural_network(np_sessions[i], np_weights)
    np_preds[i] = np_pred

print("\nPrediction comparisons:")
for i in range(len(sessions)):
    print(f"Session {i} predictions: scratch = {scratch_preds[i]:.4f},  NumPy = {np_preds[i]:.4f}")


if np.allclose(scratch_preds, np_preds):
    # If the preds are close within a very small tolerance, print that they match,
    # otherwise print that they don't
    print("Preds match!")
else: print("Preds do not match!")

"""
The preds match!
If there were ten thousand terms, the preds would probably not be an exact match
because NumPy can perform the dot prod operation in any order it would like, which
would probably cause the floating point number to be rounded every so slightly differently
in the end.
"""   



Prediction comparisons:
Session 0 predictions: scratch = 0.9800,  NumPy = 0.9800
Session 1 predictions: scratch = 1.1100,  NumPy = 1.1100
Session 2 predictions: scratch = 1.1500,  NumPy = 1.1500
Session 3 predictions: scratch = 1.0800,  NumPy = 1.0800
Preds match!


'\nThe preds match!\nIf there were ten thousand terms, the preds would probably not be an exact match\nbecause NumPy can perform the dot prod operation in any order it would like, which\nwould probably cause the floating point number to be rounded every so slightly differently\nin the end.\n'

In [5]:
Part 3 -- Multiple Outputs

<class 'SyntaxError'>: invalid syntax (<ipython-input-5-4e1c13bb9dce>, line 1)

In [6]:
import numpy as np

# used ai to debug code and understand the numpy section

def ele_mul(scalar, vector): # Function used to scale each weight by an input value
    output = [0] * len(vector)
    for i in range(len(vector)):
        output[i] = scalar * vector[i]
    return output

weights = [0.3, 0.2, 0.9] # 1 input with 3 outputs [open to the left, strike high, feint]
balance = [0.65, 0.80, 0.80, 0.90] # balance reading

# function will take an input and the weights to return 3 separate predictions
def neural_network(input, weights): 
    pred = ele_mul(input, weights)
    return pred

# function will do 1 senseing of balance
for input in balance: # cycles through all 4 elements in balance
    pred = neural_network(input, weights) # current element in cycle
    print(pred) # result of element n

print ("Numpy's Version")

# numpy requires arrays
weights_np = np.array(weights)

def np_neural_network(input, weights):
    pred = input * weights
    return pred

for input in balance:
    pred = np_neural_network(input, weights_np)
    print(pred)

# the usage of ele_mul is not needed for this version becuase numpy will do elementwise multiplication 
# when interacting with arrays. It essentially multiplies each element in the array by the input we give it, 
# removing the need for a loop. It allows us to remove everything from ele_mul from the code alltogether


[0.195, 0.13, 0.5850000000000001]
[0.24, 0.16000000000000003, 0.7200000000000001]
[0.24, 0.16000000000000003, 0.7200000000000001]
[0.27, 0.18000000000000002, 0.81]
Numpy's Version
[0.195 0.13  0.585]
[0.24 0.16 0.72]
[0.24 0.16 0.72]
[0.27 0.18 0.81]


In [7]:
Part 4 -- Multi-in/Multi-out

<class 'SyntaxError'>: invalid syntax (<ipython-input-7-d7feff58e544>, line 1)

In [8]:
def ele_mul(number, vector):
    output = [0] * len(vector)
    for i in range(len(vector)):
        output[i] = number * vector[i]
    return output

weights = [0.3,.2,.9]

def neural_network(input, weights):
    pred = ele_mul(input, weights)
    return pred

# ---- One sensing of balance ----
balance = [0.65, 0.80, 0.80, 0.90]
input = balance[0]
pred = neural_network(input, weights)
print(pred) # [0.195, 0.13, 0.5850000000000001]

def vect_mat_mul(vector, matrix):
    output = [0] * len(matrix)
    for i in range(len(matrix)):
        output[i] = w_sum(vector,
                          matrix[i])
    return output

# angle balance breath
weights = [[0.1, 0.1, -0.3], # opens left?
            [0.1, 0.2, 0.0], # strikes high?
            [0.0, 1.3, 0.1]] # feints?

input = [8.5, .65, 1.2]
pred = vect_mat_mul(input, weights)
print(pred) # [0.555, 0.9800000000000001, 0.9650000000000001]

 # ---- Two weight matrices ----
# angle balance breath
ih_wgt = [[0.1, 0.2, -0.1], # -> hid[0]
            [-0.1, 0.1, 0.9], # -> hid[1]
            [0.1, 0.4, 0.1]] # -> hid[2]

# hid0 hid1 hid2
hp_wgt = [[0.3, 1.1, -0.3], # -> opens left?
            [0.1, 0.2, 0.0], # -> strikes high?
            [0.0, 1.3, 0.1]] # -> feints?

weights = [ih_wgt, hp_wgt]

def neural_network(input, weights):
    hid = vect_mat_mul(input, weights[0]) # layer 1
    pred = vect_mat_mul(hid, weights[1]) # layer 2
    return pred

input = [8.5, 0.65, 1.2]
pred = neural_network(input, weights)
print(pred) # [0.21350000000000002, 0.14500000000000002, 0.5065]



[0.195, 0.13, 0.5850000000000001]
[0.555, 0.9800000000000001, 0.9650000000000001]
[0.21350000000000002, 0.14500000000000002, 0.5065]


In [9]:
Part 5 -- Stacking Layers

<class 'SyntaxError'>: invalid syntax (<ipython-input-9-5bc0cb0b5ab3>, line 1)

In [10]:
import numpy as np


# Weighted sum function from part 2
# Weighted sum function, takes input vector (a) and
# computes the dot product with weight vector (b)
# Returns weighted_sum (A.K.A. the dot product)
def w_sum(a, b):
    assert len(a) == len(b) #makes sure the vectors are the same length
    weighted_sum = 0 # init w_sum total to 0
    for i in range(len(a)):
        # For all of the inputs and weights, multiply the input at the i'th
        # index with the weight at the same index and add that to the w_sum total
        weighted_sum += a[i]*b[i]
    return weighted_sum


# Function that does dot product on each vector in a matrix
def vect_mat_mul(vect, matrix):
    output = [0] * len(matrix)
    for i in range(len(matrix)):
        output[i] = w_sum(vect, matrix[i])
    return output

# The two layer neutral network
def neural_network(input, weights):
  hidden = vect_mat_mul(input, weights[0])
  prediction = vect_mat_mul(hidden, weights[1])

  return hidden, prediction


blade_angle = [8.5, 9.5, 9.9, 9.0]
balance = [0.65, 0.80, 0.80, 0.90]
breath = [1.2, 1.3, 0.5, 1.0]


input = [8.5, 0.65, 1.2]

# This is going to be the hidden layer!
ih_wgt = [[0.1, 0.2, -0.1,],
          [-0.1, 0.1, 0.9],
          [0.1, 0.4, 0.1]]



# This is going to me the predction layer!
hp_wgt = [[0.3, 1.1, -0.3],
          [0.1, 0.2,  0.0],
          [0.0, 1.3, 0.1]]



weights = [ih_wgt, hp_wgt]

# This will run the network on all four sparring senses
for i in range(4):
  input = [blade_angle[i], balance[i], breath[i]]

  hidden, prediction = neural_network(input, weights)

  print("Sensing", i)
  print("Hidden Values:", hidden)
  print("Final prediction:", prediction)
                                      

# Answering the Question
# The hidden values are created by the first layer of the neural netowrk.
# Each hidden value combines the three weights.
#
# I would say for the middle lyaer to be useful it would need an activation function.
# So it can learn more complex relationships




# ----- This is going to be the Numpy version-----

blade_angle = [8.5, 9.5, 9.9, 9.0]
balance = [0.65, 0.80, 0.80, 0.90]
breath = [1.2, 1.3, 0.5, 1.0]

# The input is now going to be the hidden weights
ih_wgt = np.array([[0.1, 0.2, -0.1],
                   [-0.1, 0.1, 0.9],
                   [0.1, 0.4, 0.1]])



# This is going to be the prediction weights
hp_wgt = np.array([[0.3, 1.1, -0.3],
                   [0.1, 0.2, 0.0],
                   [0.0, 1.3, 0.1]])

# This is going to run all four sparring sensings
for i in range(4):
  input = np.array([blade_angle[i], balance[i], breath[i]])

  # Calculate the hidden layer by using dot product
  hidden = input.dot(ih_wgt.T)

  # Calculate the final prediction using the hidden layer
  prediction = hidden.dot(hp_wgt.T)

  print("Numpy Sensing", i)
  print("Numpy Hidden Values:", hidden)
  print("Numpy Final Predictions:", prediction)

Sensing 0
Hidden Values: [0.8600000000000001, 0.29499999999999993, 1.23]
Final prediction: [0.21350000000000002, 0.14500000000000002, 0.5065]
Sensing 1
Hidden Values: [0.9800000000000001, 0.30000000000000004, 1.4]
Final prediction: [0.20400000000000013, 0.15800000000000003, 0.53]
Sensing 2
Hidden Values: [1.1, -0.46000000000000013, 1.36]
Final prediction: [-0.5840000000000003, 0.017999999999999988, -0.4620000000000002]
Sensing 3
Hidden Values: [0.9800000000000001, 0.08999999999999997, 1.36]
Final prediction: [-0.015000000000000013, 0.11600000000000002, 0.253]
Numpy Sensing 0
Numpy Hidden Values: [0.86  0.295 1.23 ]
Numpy Final Predictions: [0.2135 0.145  0.5065]
Numpy Sensing 1
Numpy Hidden Values: [0.98 0.3  1.4 ]
Numpy Final Predictions: [0.204 0.158 0.53 ]
Numpy Sensing 2
Numpy Hidden Values: [ 1.1  -0.46  1.36]
Numpy Final Predictions: [-0.584  0.018 -0.462]
Numpy Sensing 3
Numpy Hidden Values: [0.98 0.09 1.36]
Numpy Final Predictions: [-0.015  0.116  0.253]
